# Ex1: Draw a triangle

In [15]:
function drawtri(n::Integer)
    n < 0 && throw(ArgumentError("'n' must be a non-negative integer"))
    println("o")
    for i in 0:n-1
        println("|", " "^i, "\\")
    end
    println("o", "-"^n, "o")
end

drawtri (generic function with 1 method)

In [16]:
drawtri(0)

o
oo


In [17]:
drawtri(1)

o
|\
o-o


In [19]:
drawtri(5)

o
|\
| \
|  \
|   \
|    \
o-----o


# Ex2: Revert a list

In [24]:
function revert(v::Vector{<:Any})
    len = length(v)
    l = 1
    r = len
    while l < r
        t = v[l]
        v[l] = v[r]
        v[r] = t
        l += 1
        r -= 1
    end
end    

revert (generic function with 1 method)

In [25]:
l = [1, 5, 7]
revert(l)
l

3-element Vector{Int64}:
 7
 5
 1

In [28]:
l = ["n", "i", "l", "b", "o", "g"]
revert(l)
l

6-element Vector{String}:
 "g"
 "o"
 "b"
 "l"
 "i"
 "n"

# Ex3: Fibonacci numbers and the Golden ratio

In [45]:
function approxphi(n::Integer)::Float64
    n < 0 && throw(ArgumentError("'n' must be a non-negative integer"))
    a = BigInt(1)
    b = BigInt(1)
    for i in 2:n
        t = b
        b = a + b
        a = t
    end
    return Float64(b/a)
end

approxphi (generic function with 1 method)

In [46]:
approxphi(1)

1.0

In [47]:
approxphi(3)

1.5

In [48]:
approxphi(100)

1.618033988749895

# Ex4: Run-length decoding

In [1]:
function rl_decode(l::Vector)
    res = ""
    for i in 1:2:length(l)
        res *= l[i+1]^l[i]
    end
    return res
end

rl_decode (generic function with 1 method)

In [2]:
rl_decode([3, 'A', 1, 'B', 2, 'C', 1, 'D'])

"AAABCCD"

In [3]:
rl_decode([3, '1', 4, '5'])

"1115555"

In [4]:
rl_decode([])

""

# Ex5: Arnold’s cat

In [6]:
function catmap(x::Int, y::Int, n::Int)
    return ((2 * x + y) % n, (x + y) % n)
end

catmap (generic function with 1 method)

In [9]:
catmap(5, 1, 7)

(4, 6)

In [10]:
function catperiod(x::Int, y::Int, n::Int)
    initial = (x, y)
    x, y = catmap(x, y, n)
    n_iter = 1
    while (x, y) != initial
        x, y = catmap(x, y, n)
        n_iter += 1
    end
    return n_iter
end

catperiod (generic function with 1 method)

In [11]:
catperiod(0, 0, 7)

1

In [12]:
catperiod(5, 1, 7)

8

In [13]:
catperiod(2, 3, 9)

12

# Ex6: Local minima of a list

In [25]:
function localmin(v::Vector{<:Real})
    local_mins = Int[]
    len = length(v)
    for i in 1:len
        i != 1 && v[i] > v[i-1] && continue
        i != len && v[i] > v[i+1] && continue
        push!(local_mins, i)
    end
    return local_mins
end

localmin (generic function with 1 method)

In [26]:
localmin(Real[])

Int64[]

In [27]:
localmin([5])

1-element Vector{Int64}:
 1

In [28]:
localmin([3, 2, 0, 1, 5, 8, 7])

2-element Vector{Int64}:
 3
 7

In [29]:
localmin([2, 2, 2, 2])

4-element Vector{Int64}:
 1
 2
 3
 4

# Ex7: Atbash cipher

In [47]:
function atbashmap(c::Char)
    return Char(219 - Int(c))
end

function atbash(s::String)
    return join(atbashmap(c) for c in collect(s))
end

atbash (generic function with 1 method)

In [48]:
atbash("abc")

"zyx"

In [49]:
atbash("abcdefghijklmnopqrstuvwxyz")

"zyxwvutsrqponmlkjihgfedcba"

In [50]:
atbash(atbash("twice"))

"twice"

# Ex8: Leibniz pie

In [56]:
function leibnizpi(n::Int)
    n < 1 && throw(ArgumentError("'n' must be a positive integer"))
    return 4 * sum((-1)^(i + 1) / (2*i - 1) for i in 1:n)
end

leibnizpi (generic function with 1 method)

In [57]:
leibnizpi(1)

4.0

In [61]:
leibnizpi(10000) == 3.1414926535900345

true

# Ex9: A list through a list

In [1]:
function listbylist(l::Vector, ind::Vector{Int}, skip::Bool=true)
    res = eltype(l)[]
    len = length(l)
    for i in ind
        if 1 <= i <= len
            push!(res, l[i])
        elseif skip
            continue
        else
            error("index $i is invalid")
        end
    end  
    return res
end

listbylist (generic function with 2 methods)

In [2]:
listbylist(["a", "b", "c"], [1, 0, 0, 2, 1], true)

3-element Vector{String}:
 "a"
 "b"
 "a"

In [5]:
listbylist(['a', 'b', 'c'], [1, -1, 0, 2, 3], false)

LoadError: index -1 is invalid

In [6]:
 listbylist(['b', 'g', 'i', 'l', 'n', 'o'], [2, 6, 1, 4, 3, 5])

6-element Vector{Char}:
 'g': ASCII/Unicode U+0067 (category Ll: Letter, lowercase)
 'o': ASCII/Unicode U+006F (category Ll: Letter, lowercase)
 'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)
 'l': ASCII/Unicode U+006C (category Ll: Letter, lowercase)
 'i': ASCII/Unicode U+0069 (category Ll: Letter, lowercase)
 'n': ASCII/Unicode U+006E (category Ll: Letter, lowercase)

# Ex10: Outer product

In [7]:
function outer(v::Vector{<:Real}, w::Vector{<:Real})
    return [[l*r for r in w] for l in v]
end

outer (generic function with 1 method)

In [8]:
outer([1, 2], [3, 4])

2-element Vector{Vector{Int64}}:
 [3, 4]
 [6, 8]

In [9]:
outer([2, 5], [1, 0, 3])

2-element Vector{Vector{Int64}}:
 [2, 0, 6]
 [5, 0, 15]

# Ex11: Second maximum

In [1]:
function secondmax(l::Vector{Int})
    f = 0
    s = 0
    for x in l
        x <= 0 && throw(ArgumentError("'l' must be a list of positive integers"))
        x >= f && (s = f; f = x)
    end
    return s
end

secondmax (generic function with 1 method)

In [2]:
secondmax([2, 5, 1, 6, 3])

5

In [3]:
secondmax([8, 2, 5, 8, 6])

8

In [4]:
secondmax([2])

0

In [6]:
secondmax(Int[])

0

# Ex12: Permutation?

In [2]:
function isperm(l::Vector{Int})
    len = length(l)
    seen = falses(len)
    for i in 1:len
        1 <= l[i] <= len && seen[l[i]] == false ? seen[l[i]] = true : return false
    end
    return true
end

isperm (generic function with 1 method)

In [4]:
isperm([1])

true

In [5]:
isperm([5, 1, 0, 3, 2, 4])

false

In [6]:
isperm([6, 2, 1, 4, 3, 5])

true

# Ex13: Catalan numbers

In [1]:
using BenchmarkTools

In [43]:
function catalan(n::Int)::Vector{Int}
    n < 1 && throw(ArgumentError("'n' should be a positive integer"))
    res = zeros(Int, n)
    res[1] = 1
    for i in 2:n
        res[i] = sum(res[1 : i-1] .* reverse(res[1 : i-1]))
    end
    return res
end

catalan (generic function with 1 method)

In [44]:
function catalan_v2(n::Int)::Vector{Int}
    n < 1 && throw(ArgumentError("'n' should be a positive integer"))
    res = zeros(Int, n)
    res[1] = 1
    for i in 2:n
        for j in 1:(i-1)
            res[i] += res[j] * res[i-j]
        end
    end
    return res
end

catalan_v2 (generic function with 1 method)

In [45]:
catalan(11)

11-element Vector{Int64}:
     1
     1
     2
     5
    14
    42
   132
   429
  1430
  4862
 16796

In [46]:
catalan_v2(11)

11-element Vector{Int64}:
     1
     1
     2
     5
    14
    42
   132
   429
  1430
  4862
 16796

In [47]:
@btime catalan(20)

  1.800 μs (77 allocations: 10.59 KiB)


20-element Vector{Int64}:
          1
          1
          2
          5
         14
         42
        132
        429
       1430
       4862
      16796
      58786
     208012
     742900
    2674440
    9694845
   35357670
  129644790
  477638700
 1767263190

In [48]:
@btime catalan_v2(20)

  517.236 ns (1 allocation: 224 bytes)


20-element Vector{Int64}:
          1
          1
          2
          5
         14
         42
        132
        429
       1430
       4862
      16796
      58786
     208012
     742900
    2674440
    9694845
   35357670
  129644790
  477638700
 1767263190

In [52]:
function catalan_bigint(n::Int)::Vector{BigInt}
    n < 1 && throw(ArgumentError("'n' should be a positive integer"))
    res = zeros(BigInt, n)
    res[1] = BigInt(1)
    for i in 2:n
        res[i] = sum(res[1 : i-1] .* reverse(res[1 : i-1]))
    end
    return res
end

catalan_bigint (generic function with 1 method)

In [53]:
function catalan_v2_bigint(n::Int)::Vector{BigInt}
    n < 1 && throw(ArgumentError("'n' should be a positive integer"))
    res = zeros(BigInt, n)
    res[1] = BigInt(1)
    for i in 2:n
        for j in 1:(i-1)
            res[i] += res[j] * res[i-j]
        end
    end
    return res
end

catalan_v2_bigint (generic function with 1 method)

In [58]:
@btime catalan_bigint(100)

  312.792 μs (15550 allocations: 458.08 KiB)


100-element Vector{BigInt}:
                                                         1
                                                         1
                                                         2
                                                         5
                                                        14
                                                        42
                                                       132
                                                       429
                                                      1430
                                                      4862
                                                     16796
                                                     58786
                                                    208012
                                                         ⋮
        64633260585762914370496637486146181462681535261000
       254224158304000796523953440778841647086547372026600
      1000134600800354781929

In [59]:
@btime catalan_v2_bigint(100)

  399.875 μs (24755 allocations: 558.09 KiB)


100-element Vector{BigInt}:
                                                         1
                                                         1
                                                         2
                                                         5
                                                        14
                                                        42
                                                       132
                                                       429
                                                      1430
                                                      4862
                                                     16796
                                                     58786
                                                    208012
                                                         ⋮
        64633260585762914370496637486146181462681535261000
       254224158304000796523953440778841647086547372026600
      1000134600800354781929