# Ex1: List muxer

In [104]:
function muxer(l::Vector)
    len1 = length(l)
    len1 > 0 && (len2 = length(l[1]))
    return [l[i][j] for j in 1:len2 for i in 1:len1]
end

muxer (generic function with 1 method)

In [83]:
muxer([['a', 'b'], ['c', 'd']])

4-element Vector{Char}:
 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
 'c': ASCII/Unicode U+0063 (category Ll: Letter, lowercase)
 'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)
 'd': ASCII/Unicode U+0064 (category Ll: Letter, lowercase)

In [84]:
muxer([['a', 'b']])

2-element Vector{Char}:
 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
 'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)

In [85]:
muxer([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

12-element Vector{Int64}:
  1
  4
  7
 10
  2
  5
  8
 11
  3
  6
  9
 12

# Ex2: Periodic Fibonacci sequences

In [40]:
function fibperiod(n::Int)
    n <= 1 && throw(ArgumentError("'n' must be an integer >1"))
    a = 1
    b = 1
    count = 1
    while !(a == 0 && b == 1)
        t = b
        b = (a + t) % n
        a = t
        count += 1
    end
    return count
end

fibperiod (generic function with 1 method)

In [41]:
fibperiod(2)

3

In [42]:
fibperiod(7)

16

In [43]:
fibperiod(1001)

560

# Ex3: And the CPU’s for free

In [10]:
function interestdays(x::Float64, y::Float64, r::Float64)
    (x < 0 || y < 0 || r < -100) && throw(ArgumentError("some of the arguments are misspecified"))
    days = 0
    x == y && return 0
    (y - x) * x * r * (y + (r == -100)) <= 0 && return nothing
    while (y - x) * r > 0
        x *= (1 + r/100)
        days += 1
    end
    return days
end

interestdays (generic function with 1 method)

In [11]:
interestdays(3.0, 3.0, 0.01)

0

In [18]:
interestdays(1.0, 0., -100.)

1

In [12]:
interestdays(3.0, 4.0, 0.0)

In [13]:
interestdays(3.0, 0.0, -0.01)

In [14]:
interestdays(3.0, 4.0, -0.01)

In [15]:
interestdays(0.5, 1.0, 0.1)

694

In [16]:
interestdays(1.0, 0.5, -0.1)

693

# Ex4: Run-length encoding

In [42]:
function rl_encode(s::String)
    res = []
    cur_char = nothing
    cur_count = 0
    for char in collect(s)
        if char != cur_char
            cur_char != nothing && push!(res, cur_count, cur_char)
            cur_count = 0
            cur_char = char
        end
        cur_count += 1
    end
    cur_char != nothing && push!(res, cur_count, cur_char)
    return res
end

rl_encode (generic function with 1 method)

In [43]:
rl_encode("AAABCCD")

8-element Vector{Any}:
 3
  'A': ASCII/Unicode U+0041 (category Lu: Letter, uppercase)
 1
  'B': ASCII/Unicode U+0042 (category Lu: Letter, uppercase)
 2
  'C': ASCII/Unicode U+0043 (category Lu: Letter, uppercase)
 1
  'D': ASCII/Unicode U+0044 (category Lu: Letter, uppercase)

In [47]:
rl_encode("1115555")

4-element Vector{Any}:
 3
  '1': ASCII/Unicode U+0031 (category Nd: Number, decimal digit)
 4
  '5': ASCII/Unicode U+0035 (category Nd: Number, decimal digit)

In [46]:
rl_encode("")

Any[]

# Ex4: Sublist?

In [54]:
function issublist(l1::Vector, l2::Vector)
    eltype(l1) == eltype(l2) || throw(ArgumentError("'l1' and 'l2' must be of the same type"))
    len1 = length(l1)
    len2 = length(l2)
    for start in 1:(len2 - len1 + 1)
        for i in 1:len1
            l1[i] == l2[start + i - 1] || @goto endcheck
        end
        return true
        @label endcheck
    end
    return false
end

issublist (generic function with 1 method)

In [55]:
issublist([], [])

true

In [56]:
issublist([1,2], [1,2,3,2,1,0])

true

In [57]:
issublist([1,3], [1,2,3,2,1,0])

false

In [58]:
issublist([2,3,2,1], [1,2,3,2,1,0])

true

# Ex5: Supermarket queue

In [64]:
function supermarket(l::Vector{Int}, k::Int)
    k < 1 && throw(ArgumentError("'k' must be a positive integer"))
    times = zeros(Int, k)
    counts = zeros(Int, k)
    for t in l
        ind = findmin(times)[2]
        times[ind] += t
        counts[ind] += 1
    end
    return (findmax(times), findmax(counts))
end

supermarket (generic function with 1 method)

In [65]:
supermarket([3, 10, 2, 6, 2], 1)

((23, 1), (5, 1))

In [66]:
supermarket([3, 10, 2, 6, 2], 2)

((12, 2), (3, 1))

In [68]:
supermarket([3, 10, 2, 6, 2], 3)

((10, 2), (2, 1))

In [67]:
supermarket([3, 10, 2, 6, 2], 10)

((10, 2), (1, 1))

# Ex6: Evenly split a list

In [2]:
function listsplit(l::Vector{Int})
    len = length(l)
    total = sum(l)
    ind = 0
    currsum = 0
    currbest = abs(total)
    for i in 1 : len - 1
        currsum += l[i]
        delta = abs(total - 2 * currsum)
        delta < currbest && (ind = i; currbest = delta)
    end
    return ind
end

listsplit (generic function with 1 method)

In [3]:
listsplit([2,4,-1,5,-2])

3

In [4]:
listsplit([2,4,5,11])

3

In [5]:
listsplit([1,2,3,-6])

0

In [6]:
listsplit([5,5,5])

1

In [7]:
listsplit(Int[])

0

In [8]:
listsplit([3])

0

# Ex7: Avalanches

In [19]:
function avalanche(l::Vector{Int}, k::Int=2)
    len = length(l)
    push!(l, 0)
    breaker = false
    while !breaker
        l[end] = 0
        breaker = true
        for i in 1:len
            l[i] - l[i+1] >= k && (l[i] -= 1; l[i+1] += 1; breaker = false)
        end
    end
    pop!(l)
    return l
end

avalanche (generic function with 2 methods)

In [21]:
avalanche([6, 4, 1])

3-element Vector{Int64}:
 3
 2
 1

In [22]:
avalanche([6, 4, 1], 3)

3-element Vector{Int64}:
 5
 4
 2

In [23]:
avalanche([15, 7, 6, 1], 4)

4-element Vector{Int64}:
 11
  9
  6
  3

In [24]:
avalanche([3], 2)

1-element Vector{Int64}:
 1

# Ex8: Longest ramp

In [32]:
function longestramp(v::Vector{Int})
    push!(v, -1)
    len = length(v)
    i0 = i1 = 0
    l = 1
    for i in 2:len
        if v[i] < v[i-1]
            (i - l) > (i1 - i0) && (i0 = l; i1 = i)
            l = i
        end
    end
    pop!(v)
    return (i0, i1)
end

longestramp (generic function with 1 method)

In [26]:
a = b = 1
a

1

In [33]:
longestramp([5, 6, 7])

(1, 4)

In [27]:
ddb

1

In [34]:
longestramp([1, 3, 1, 2, 3])

(3, 6)

In [35]:
longestramp([2, 3, 3, 1, 6, 1, 1, 3])

(1, 4)

In [36]:
longestramp([3, 2, 5, 5, 1, 1, 4, 5, 2, 6])

(5, 9)

In [38]:
longestramp(Int[])

(0, 0)

In [39]:
longestramp([7])

(1, 2)

# Ex9: Regular numbers

In [66]:
function isregular(n::Int)
    n <= 0 && throw(ArgumentError("'n' must be a positive integer"))
    return n == 1 || any(n % k == 0 && isregular(n÷k) for k in [2, 3, 5])
end

isregular (generic function with 1 method)

In [67]:
isregular(7)

false

In [68]:
isregular(10)

true

In [69]:
isregular(2^5*3^5*5^5)

true

In [70]:
isregular(2^5*3^5*5^5*7)

false

# Ex10: Confluence of prioritized queues

In [96]:
function confluence(q1::Vector{Int}, q2::Vector{Int})::Vector{Tuple{Int, Int}}
    l1, l2 = length(q1), length(q2)
    i1 = i2 = 1
    p1 = p2 = 0
    res = Tuple{Int, Int}[]
    while i1 <= l1 && i2 <= l2
        if p1 + q1[i1] >= p2 + q2[i2]
            push!(res, (1, q1[i1]))
            i1 += 1
            p2 += 1
        else
            push!(res, (2, q2[i2]))
            i2 += 1
            p1 += 1
        end
    end
    i2 > l2 && push!(res, ((1, q1[i]) for i in i1:l1)...)
    i1 > l1 && push!(res, ((2, q2[i]) for i in i2:l2)...)
    return res
end

confluence (generic function with 1 method)

In [99]:
confluence(Int[], Int[])

Tuple{Int64, Int64}[]

In [100]:
confluence([3, 4], Int[])

2-element Vector{Tuple{Int64, Int64}}:
 (1, 3)
 (1, 4)

In [103]:
confluence([3, 2, 1], [1, 4, 7, 2, 9]) == [(1, 3), (1, 2), (2, 1), (2, 4), (2, 7), (1, 1), (2, 2), (2, 9)]

true

# Ex11: Counting sort

In [158]:
function countsort(l::Vector{Int}, k::Int)
    counts = zeros(Int, k)
    for x in l
        counts[x] += 1
    end
    curr = 1
    for i in 1:k
        l[curr:curr + counts[i] - 1] .= i
        curr += counts[i]
    end
    return l
end

countsort (generic function with 1 method)

In [159]:
countsort([3, 5, 2, 1, 3], 6)

5-element Vector{Int64}:
 1
 2
 3
 3
 5

In [160]:
countsort([3, 5, 2, 1, 2, 1, 3], 10)

7-element Vector{Int64}:
 1
 1
 2
 2
 3
 3
 5

In [161]:
countsort(Int[], 6)

Int64[]

In [162]:
l = [3, 5, 2, 1, 3]
countsort(l, 7)
l

5-element Vector{Int64}:
 1
 2
 3
 3
 5

# Ex12: List partitioning

In [170]:
function listpart(l::Vector{Int}, k::Int)::Vector{Vector{Int}}
    res = Vector{Int}[]
    curr_list = Int[]
    curr_sum = 0
    for x in l
        x > k && continue
        curr_sum += x
        if curr_sum > k
            push!(res, curr_list)
            curr_list = [x]
            curr_sum = x
        else
            push!(curr_list, x)
        end
    end
    curr_list != [] && push!(res, curr_list)
    return res
end

listpart (generic function with 1 method)

In [171]:
listpart(Int[4, 3, 2], 7)

2-element Vector{Vector{Int64}}:
 [4, 3]
 [2]

In [172]:
listpart([4, 3, 2], 5)

2-element Vector{Vector{Int64}}:
 [4]
 [3, 2]

In [173]:
listpart([4, 3, 2], 10)

1-element Vector{Vector{Int64}}:
 [4, 3, 2]

In [174]:
listpart([3, 4, 2, 6, 1], 8)

3-element Vector{Vector{Int64}}:
 [3, 4]
 [2, 6]
 [1]

In [175]:
listpart([4, 1, 8, 1], 7)

1-element Vector{Vector{Int64}}:
 [4, 1, 1]

In [176]:
listpart([4, 3, 6], 2)

Vector{Int64}[]

In [178]:
listpart(Int[], 2)

Vector{Int64}[]